services:
  app:
    image: referral-service
    build: .
    networks:
      - backend
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    env_file:
      - ".env"
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - database-pg:/var/lib/postgresql/data
    env_file:
      - ".env"


networks:
  backend:
    driver: bridge

volumes:
  database-pg: